import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const slug = "camera-ingest-preflight";
const licenseKey = `sb_license:${slug}`;
const verdictKey = `sb_license_verdict:${slug}`;
const root = process.cwd();
const cli = resolve(root, "target/debug/camera-ingest-preflight");

type CliRun = { status: number | null; stdout: string; stderr: string };
type DemoReport = { root: string; generated_unix_seconds: number; summary: { files_scanned: number; ready: number; review: number; rejected: number; gps_files: number }; files: unknown[] };

function verdictFor(token: string, valid: boolean) {
  return {
    valid,
    reason: valid ? "ok" : "invalid",
    checkedAt: Date.now(),
    tokenFingerprint: createHash("sha256").update(token).digest("hex")
  };
}

function runCli(args: string[]): CliRun {
  const result = spawnSync(cli, args, { cwd: root, encoding: "utf8" });
  if (result.error) throw result.error;
  return { status: result.status, stdout: result.stdout ?? "", stderr: result.stderr ?? "" };
}

function bundledDemo(profile = "photoprism") {
  const result = runCli(["demo", "--profile", profile]);
  expect(result.status).toBe(1);
  const folder = result.stdout.match(/^DEMO   sample card and JSON report → (.+)$/m)?.[1];
  expect(folder).toBeTruthy();
  const report = JSON.parse(readFileSync(resolve(folder!, "preflight-demo.json"), "utf8")) as DemoReport;
  return { ...result, folder: folder!, report };
}

function stableReport(report: DemoReport): DemoReport {
  return { ...report, root: "<temporary demo folder>/card", generated_unix_seconds: 0 };
}

async function seedLicense(page: import("@playwright/test").Page, token: string, valid: boolean) {
  const verdict = verdictFor(token, valid);
  await page.addInitScript(({ licenseKey, verdictKey, token, verdict }) => {
    localStorage.setItem(licenseKey, token);
    localStorage.setItem(verdictKey, JSON.stringify(verdict));
  }, { licenseKey, verdictKey, token, verdict });
}

test("@claim:sample-scan /demo preloads the four-file report generated by the bundled CLI", async ({ page }) => {
  const errors: string[] = [];
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/demo/");
  await expect(page).toHaveTitle("Demo — Camera Ingest Preflight");
  await expect(page.getByText("Demo — sample data, nothing is saved.")).toBeVisible();
  await expect(page.locator("#report-body tr")).toHaveCount(4);
  await expect(page.locator("#summary-files")).toHaveText("4");
  await expect(page.locator("#summary-ready")).toHaveText("0");
  await expect(page.locator("#summary-review")).toHaveText("3");
  await expect(page.locator("#summary-reject")).toHaveText("1");
  await expect(page.locator("#report-body").getByText("Proprietary Insta360 original requires vendor conversion or a tested downstream decoder.")).toBeVisible();
  await expect(page.locator("#demo-transcript")).toContainText("FILES    4   READY    0   REVIEW    3   REJECT    1");
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.locator("main")).toHaveCount(1);
  await expect(page.locator("h1")).toHaveCount(1);
  await expect(page.locator("img:not([alt])")).toHaveCount(0);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((item) => ["serious", "critical"].includes(item.impact ?? ""))).toEqual([]);
  expect(errors).toEqual([]);
});

test("@regression:cli-web-sample-parity the published report and transcript exactly match camera-ingest-preflight demo", () => {
  const fixtures = JSON.parse(readFileSync(resolve(root, "site/public/demo-fixtures.json"), "utf8")) as Record<string, { report: DemoReport; transcript: string }>;
  const actual = bundledDemo("photoprism");
  expect(stableReport(actual.report)).toEqual(fixtures.photoprism.report);
  expect(actual.stdout.replaceAll(actual.folder, "<temporary demo folder>")).toBe(fixtures.photoprism.transcript);
});

test("@claim:read-only-scan bundled CLI input remains unchanged after scanning", () => {
  const originals = ["FISHEYE_007.DNG", "RICOH_001.JPG", "SONY_A73_042.ARW", "VID_018.INSV"];
  const before = originals.map((name) => createHash("sha256").update(readFileSync(resolve(root, "examples/demo-card/DCIM", name))).digest("hex"));
  const actual = bundledDemo();
  expect(actual.report.summary.files_scanned).toBe(4);
  const after = originals.map((name) => createHash("sha256").update(readFileSync(resolve(root, "examples/demo-card/DCIM", name))).digest("hex"));
  expect(after).toEqual(before);
});

test("@claim:gps-redaction CLI reports GPS presence without coordinates unless explicitly requested", () => {
  const actual = bundledDemo();
  const encoded = JSON.stringify(actual.report);
  expect(actual.report.summary.gps_files).toBe(1);
  expect(encoded).toContain("gps_coordinates_included\":false");
  expect(encoded).not.toContain("latitude");
  expect(encoded).not.toContain("longitude");
});

test("@claim:sha256-report each scanned original receives its matching SHA-256 digest", () => {
  const actual = bundledDemo();
  const files = actual.report.files as Array<{ path: string; sha256: string }>;
  expect(files).toHaveLength(4);
  for (const file of files) {
    expect(file.sha256).toMatch(/^[a-f0-9]{64}$/);
    const source = readFileSync(resolve(root, "examples/demo-card", file.path));
    expect(file.sha256).toBe(createHash("sha256").update(source).digest("hex"));
  }
});

test("@claim:local-cli-privacy the CLI has no telemetry or network client dependency", () => {
  const manifest = readFileSync(resolve(root, "Cargo.toml"), "utf8");
  const sources = ["src/lib.rs", "src/main.rs"].map((file) => readFileSync(resolve(root, file), "utf8")).join("\n");
  expect(manifest).not.toMatch(/reqwest|ureq|hyper|tokio|telemetry|analytics/i);
  expect(sources).not.toMatch(/TcpStream|UdpSocket|std::net|telemetry|analytics|http:/i);
  expect(bundledDemo().report.summary.files_scanned).toBe(4);
});

test("@claim:json-csv-exit-codes CLI exports JSON and CSV, ignores symlinks, and returns documented errors", () => {
  const fixture = mkdtempSync("/tmp/camera-ingest-preflight-claim-");
  const card = resolve(fixture, "card");
  const outside = resolve(fixture, "outside.bin");
  const json = resolve(card, "preflight.json");
  const csv = resolve(card, "preflight.csv");
  mkdirSync(card);
  writeFileSync(resolve(card, "IMG_0001.XMP"), "sidecar");
  writeFileSync(outside, "not on this card");
  symlinkSync(outside, resolve(card, "external-link.bin"));
  const result = runCli(["scan", card, "--json", json, "--csv", csv, "--quiet"]);
  expect(result.status).toBe(0);
  const report = JSON.parse(readFileSync(json, "utf8")) as { summary: { files_scanned: number }; files: Array<{ path: string }> };
  expect(report.summary.files_scanned).toBe(1);
  expect(report.files.map((file) => file.path)).toEqual(["IMG_0001.XMP"]);
  expect(readFileSync(csv, "utf8")).toContain('"IMG_0001.XMP"');
  expect(runCli(["scan", resolve(fixture, "missing-card"), "--quiet"]).status).toBe(2);
});

test("@claim:demo-sandbox demo routes are isolated, resettable, and never read real license storage", async ({ page }) => {
  const requests: string[] = [];
  page.on("request", (request) => requests.push(request.url()));
  await page.addInitScript(() => {
    const nativeGet = Storage.prototype.getItem;
    (window as Window & { demoStorageReads?: string[] }).demoStorageReads = [];
    Storage.prototype.getItem = function getItem(key: string) {
      if (key.startsWith("sb_")) (window as Window & { demoStorageReads?: string[] }).demoStorageReads?.push(key);
      return nativeGet.call(this, key);
    };
    localStorage.setItem("sb_license:camera-ingest-preflight", "REAL_LICENSE_SHOULD_NOT_BE_READ");
    localStorage.setItem("sb_migration_layouts:camera-ingest-preflight", "[]");
  });
  await page.goto("/?demo=1");
  await expect(page).toHaveTitle("Demo — Camera Ingest Preflight");
  await expect(page.getByText("Demo — sample data, nothing is saved.")).toBeVisible();
  await expect(page.locator("#report-body tr")).toHaveCount(4);
  await page.getByRole("button", { name: "Reset demo" }).click();
  await expect(page.locator("#summary-review")).toHaveText("3");
  await expect(page.getByRole("link", { name: "Start for real" })).toHaveAttribute("href", "/");
  expect(await page.evaluate(() => (window as Window & { demoStorageReads?: string[] }).demoStorageReads)).toEqual([]);
  const origin = new URL(page.url()).origin;
  expect(requests.filter((url) => new URL(url).origin !== origin)).toEqual([]);
});

for (const path of ["/privacy/", "/terms/"]) {
  test(`${path} is semantic, accessible, and has product metadata`, async ({ page }) => {
    await page.goto(path);
    await expect(page.locator("h1")).toHaveCount(1);
    await expect(page.locator('link[rel="canonical"]')).toHaveCount(1);
    await expect(page.locator('meta[property="og:image"]')).toHaveAttribute("content", /social-card\.webp$/);
    const results = await new AxeBuilder({ page }).analyze();
    expect(results.violations.filter((item) => ["serious", "critical"].includes(item.impact ?? ""))).toEqual([]);
  });
}

test("site has required social metadata, a static 404 document, and no SPA fallback", () => {
  const index = readFileSync(resolve(root, "dist/site/index.html"), "utf8");
  const notFound = readFileSync(resolve(root, "dist/site/404.html"), "utf8");
  const config = JSON.parse(readFileSync(resolve(root, "dist/site/staticwebapp.config.json"), "utf8")) as { responseOverrides: { "404": { rewrite: string } }; navigationFallback?: unknown; routes: Array<{ route: string; rewrite?: string }> };
  expect(index).toContain('rel="canonical"');
  expect(index).toContain('property="og:image"');
  expect(index).toContain('rel="apple-touch-icon"');
  expect(index).toContain(`name="build-id" content="${spawnSync("git", ["rev-parse", "--short=12", "HEAD"], { cwd: root, encoding: "utf8" }).stdout.trim()}"`);
  expect(notFound).toContain("This page was not found.");
  expect(config.navigationFallback).toBeUndefined();
  expect(config.responseOverrides["404"].rewrite).toBe("/404.html");
  expect(config.routes).toContainEqual({ route: "/demo", rewrite: "/demo/index.html" });
});

test("mobile layout keeps the primary action and CLI-backed report operable", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  const install = page.getByRole("link", { name: "Install the scanner" });
  await expect(install).toBeVisible();
  await page.getByRole("button", { name: "Try it with sample data" }).first().click();
  await expect(page.locator("#report-body").getByText("DCIM/RICOH_001.JPG", { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  const results = await new AxeBuilder({ page }).analyze();
  expect(results.violations.filter((item) => ["serious", "critical"].includes(item.impact ?? ""))).toEqual([]);
});

test("skip link transfers keyboard focus to main and the mobile wordmark is touch sized", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  const skip = page.getByRole("link", { name: "Skip to main content" });
  await skip.focus();
  await page.keyboard.press("Enter");
  await expect(page.locator("main")).toBeFocused();
  const wordmark = page.getByRole("link", { name: "CAMERA / PREFLIGHT home" });
  await expect(wordmark).toHaveAccessibleName("CAMERA / PREFLIGHT home");
  const box = await wordmark.boundingBox();
  expect(box?.width).toBeGreaterThanOrEqual(44);
  expect(box?.height).toBeGreaterThanOrEqual(44);
});

test("@claim:offline-reload production worker precaches the demo fixture and offline reload stays interactive", async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors: string[] = [];
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  page.on("pageerror", (error) => errors.push(error.message));
  const worker = readFileSync(resolve(root, "dist/site/sw.js"), "utf8");
  expect(worker).not.toContain("__PRECACHE_MANIFEST__");
  expect(worker).not.toContain("__CACHE_NAME__");
  expect(worker).toMatch(/const cacheName = "camera-preflight-shell-[a-f0-9]{12}"/);
  expect(worker).toContain('"/demo-fixtures.json"');

  await page.goto("/?demo=1");
  await expect(page.locator("#report-body tr")).toHaveCount(4);
  await page.evaluate(() => navigator.serviceWorker.ready);
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true);
  await page.context().setOffline(true);

  const missingAsset = await page.evaluate(() => fetch("/assets/missing-regression.js")
    .then(async (response) => ({ resolved: true, body: await response.text() }))
    .catch(() => ({ resolved: false, body: "" })));
  expect(missingAsset.resolved).toBe(false);
  expect(missingAsset.body).not.toContain("<!doctype html");
  errors.length = 0;
  await page.reload({ waitUntil: "domcontentloaded" });
  await expect(page.locator("#report-body tr")).toHaveCount(4);
  expect(errors).toEqual([]);
  await context.close();
});

test("Azure static deployment config preserves response policies and immutable assets", () => {
  const config = JSON.parse(readFileSync(resolve(root, "dist/site/staticwebapp.config.json"), "utf8")) as {
    globalHeaders: Record<string, string>;
    routes: Array<{ route: string; headers: Record<string, string> }>;
  };
  expect(config.globalHeaders["Content-Security-Policy"]).toContain("default-src 'self'");
  expect(config.globalHeaders["Permissions-Policy"]).toBe("camera=(), microphone=(), geolocation=()");
  expect(config.globalHeaders["X-Content-Type-Options"]).toBe("nosniff");
  expect(config.routes).toEqual(expect.arrayContaining([
    { route: "/assets/*", headers: { "Cache-Control": "public, max-age=31536000, immutable" } },
    { route: "/camera-blueprint.webp", headers: { "Cache-Control": "public, max-age=31536000, immutable" } },
    { route: "/social-card.webp", headers: { "Cache-Control": "public, max-age=31536000, immutable" } }
  ]));
});

test("@regression:license-token-cache returned invalid token never inherits an old valid verdict", async ({ page }) => {
  const oldToken = "OLD_VALID_TOKEN";
  const replacement = "NEW_INVALID_TOKEN_456";
  await seedLicense(page, oldToken, true);
  let requests = 0;
  await page.route("**/api/v1/products/camera-ingest-preflight/verify?license=*", async (route) => {
    requests += 1;
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ valid: false, reason: "invalid" }) });
  });

  await page.goto(`/?license=${replacement}`);
  await expect(page.getByText("License no longer active. Check the token or buy a new license.")).toBeVisible();
  expect(requests).toBe(1);
  await expect(page.locator("#unlocked-view")).toBeHidden();
  await expect.poll(() => page.evaluate((key) => localStorage.getItem(key), licenseKey)).toBe(replacement);
  expect(new URL(page.url()).searchParams.has("license")).toBe(false);
});

test("@claim:license-verification returned and restored tokens verify immediately while cached verdicts are token-bound", async ({ page }) => {
  const oldToken = "OLD_INVALID_TOKEN";
  const replacement = "NEW_VALID_TOKEN_456";
  await seedLicense(page, oldToken, false);
  let requests = 0;
  await page.route("**/api/v1/products/camera-ingest-preflight/verify?license=*", async (route) => {
    requests += 1;
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ valid: true, reason: "ok" }) });
  });

  await page.goto(`/?license=${replacement}`);
  await expect(page.getByText("License verified. Migration set unlocked.")).toBeVisible();
  expect(requests).toBe(1);
  await expect(page.locator("#unlocked-view")).toBeVisible();
  await page.getByRole("button", { name: "Forget license on this device" }).click();
  await page.getByRole("button", { name: "Have a license? Restore it" }).click();
  await page.getByLabel("License token").fill("RESTORED_VALID_TOKEN");
  await page.getByRole("button", { name: "Verify license" }).click();
  await expect(page.locator("#unlocked-view")).toBeVisible();
  expect(requests).toBe(2);
});

test("@claim:license-daily-check unchanged verified tokens do not make another verification request within a day", async ({ page }) => {
  const token = "CACHED_VALID_TOKEN";
  await seedLicense(page, token, true);
  let requests = 0;
  await page.route("**/api/v1/products/camera-ingest-preflight/verify?license=*", async (route) => {
    requests += 1;
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ valid: true, reason: "ok" }) });
  });
  await page.goto("/");
  await expect(page.getByText("License verified on this device.")).toBeVisible();
  expect(requests).toBe(0);
});

test("@claim:migration-brief a verified license generates, saves, prints, and downloads a local migration brief", async ({ page }) => {
  await page.addInitScript(() => {
    window.print = () => { document.documentElement.dataset.printedMigrationBrief = "true"; };
  });
  await page.route("**/api/v1/products/camera-ingest-preflight/verify?license=*", async (route) => {
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ valid: true, reason: "ok" }) });
  });
  await page.goto("/?license=VALID_MIGRATION_TOKEN");
  await expect(page.locator("#unlocked-view")).toBeVisible();

  await page.getByRole("button", { name: "Load sample report" }).click();
  const brief = page.locator("#brief-output");
  await expect(brief.getByRole("heading", { name: "PhotoPrism migration brief" })).toBeVisible();
  await expect(brief.getByText("Format-specific handoff notes")).toBeVisible();
  await expect(brief).toContainText("Exact GPS coordinates are not included in this brief.");

  await page.getByLabel("Layout name").fill("PhotoPrism card triage");
  await page.getByRole("button", { name: "Save layout" }).click();
  await expect(page.getByText("Saved PhotoPrism card triage on this browser.")).toBeVisible();
  await expect(page.getByLabel("Saved layouts")).toContainText("PhotoPrism card triage — PhotoPrism");

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download text brief" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("camera-ingest-migration-brief.txt");
  expect(await download.createReadStream().then(async (stream) => {
    const chunks: Buffer[] = [];
    for await (const chunk of stream) chunks.push(Buffer.from(chunk));
    return Buffer.concat(chunks).toString("utf8");
  })).toContain("PhotoPrism migration brief");

  await page.getByRole("button", { name: "Print brief" }).click();
  await expect.poll(() => page.evaluate(() => document.documentElement.dataset.printedMigrationBrief)).toBe("true");
});

test("@claim:pasted-report-privacy a pasted report remains in the page and creates no report upload request", async ({ page }) => {
  await page.route("**/api/v1/products/camera-ingest-preflight/verify?license=*", async (route) => {
    await route.fulfill({ contentType: "application/json", body: JSON.stringify({ valid: true, reason: "ok" }) });
  });
  await page.goto("/?license=LOCAL_REPORT_TOKEN");
  await expect(page.locator("#unlocked-view")).toBeVisible();
  const requests: string[] = [];
  page.on("request", (request) => requests.push(request.url()));
  await page.getByRole("button", { name: "Load sample report" }).click();
  await expect(page.locator("#brief-output")).toBeVisible();
  expect(requests.filter((url) => new URL(url).origin !== new URL(page.url()).origin)).toEqual([]);
  await expect(page.locator("#migration-report")).toHaveValue(/"files_scanned": 4/);
});

test("@claim:local-demo-privacy the normal sample demo uses only local fixed records and has no file picker", async ({ page }) => {
  const requests: string[] = [];
  page.on("request", (request) => requests.push(request.url()));
  await page.goto("/");
  await page.getByRole("button", { name: "Try it with sample data" }).first().click();
  await expect(page.locator("#report-body").getByText("Proprietary Insta360 original requires vendor conversion or a tested downstream decoder.")).toBeVisible();
  const origin = new URL(page.url()).origin;
  expect(requests.filter((url) => new URL(url).origin !== origin)).toEqual([]);
  await expect(page.locator('input[type="file"]')).toHaveCount(0);
});

test("@claim:open-source MIT license and source link ship with the scanner", async ({ page }) => {
  expect(readFileSync(resolve(root, "LICENSE"), "utf8")).toContain("Permission is hereby granted, free of charge");
  await page.goto("/");
  await expect(page.getByRole("link", { name: "Source and release binaries" })).toHaveAttribute("href", /github\.com\/B-Divyesh\/sf-camera-ingest-preflight$/);
});
